# Generated by Django 5.2.17 on 2026-08-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='Accounts.farmerprofile')),
            ],
        ),
    ]
