# Generated by Django 5.2.17 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='cultivation_area',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cultivation area in acres', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='delivery_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='farming_method',
            field=models.CharField(choices=[('Conventional', 'Conventional'), ('Organic', 'Organic'), ('Natural', 'Natural Farming'), ('Integrated', 'Integrated Farming')], default='Conventional', max_length=30),
        ),
        migrations.AddField(
            model_name='crop',
            name='irrigation_type',
            field=models.CharField(choices=[('Borewell', 'Borewell'), ('Canal', 'Canal'), ('Rain-fed', 'Rain-fed'), ('Drip', 'Drip Irrigation'), ('Sprinkler', 'Sprinkler')], default='Borewell', max_length=30),
        ),
        migrations.AddField(
            model_name='crop',
            name='minimum_contract_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum quantity available for contract in quintals', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='quality_grade',
            field=models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C'), ('Premium', 'Premium')], default='Grade A', max_length=30),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, help_text='Expected price per quintal', max_digits=10),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Expected production in quintals', max_digits=10),
        ),
    ]
