import { createContext, useContext, useMemo, useState } from "react";

const translations = {
  en: {
    language: "Language",
    overview: "Overview",
    about: "About",
    features: "Features",
    services: "Services",
    howItWorks: "How It Works",
    contact: "Contact",
    register: "Register",
    registerBuyer: "Register as Buyer",
    openWorkspace: "Open workspace",
    logout: "Logout",
    getStartedNav: "Get Started",
    secureFarming: "Secure Farming. Assured Market.",
    secureLogin: "Secure Login",
    welcomeBack: "Welcome back",
    email: "Email",
    emailPlaceholder: "Enter your email",
    password: "Password",
    login: "Login",
    newHere: "New here?",
    createAccount: "Create an account",
    getStarted: "Get Started",
    chooseAccount: "Choose your account",
    chooseAccountDescription: "Farmers and buyers follow separate onboarding paths so the right information can be verified.",
    farmerOnboarding: "Farmer Onboarding",
    registerFarmer: "Register as Farmer",
    farmerDescription: "Create your farmer account and connect with verified buyers.",
    buyerOnboarding: "Buyer Onboarding",
    registerCompany: "Register as Company",
    companyDescription: "Create your company account to connect with farmers and manage contract farming agreements.",
    continue: "Continue",
    aboutHero: "A better contract for every harvest",
    featuresHero: "Clarity at every stage of the growing season",
    servicesHero: "One platform for the whole agricultural network",
    howHero: "From seed plan to settled payment",
    contactHero: "Talk to the AgriContract team",
    homeEyebrow: "Digital infrastructure for better harvests",
    homeTitle: "Grow with confidence. Sell with certainty.",
    homeDescription: "AgriContract brings farmers, FPOs and responsible buyers together through verified partnerships, clear contracts and milestone-based payments.",
    registerAsFarmer: "Register as Farmer",
    registerAsCompany: "Register as Company",
    connectedNetwork: "A connected network",
    networkTitle: "Good contracts start with the right people",
    networkDescription: "Bring a dependable supply chain together before the first seed goes into the soil.",
    whyPlatform: "Why AgriContract",
    fairerPath: "A fairer path from field to market",
    workflowTitle: "One shared record for the entire season",
    workflowDescription: "Replace scattered calls and spreadsheets with a workflow that gives farmers, buyers and operations teams the same source of truth.",
    exploreWorkflow: "Explore the workflow",
    step: "Step",
    personalDetails: "Personal Details",
    farmDetails: "Farm Details",
    accountDetails: "Account Details",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    enterFirstName: "Enter first name",
    enterLastName: "Enter last name",
    enterEmail: "Enter email address",
    enterPhone: "Enter 10-digit phone number",
    createPassword: "Create a strong password",
    next: "Next",
    farmFpoName: "Farm / FPO Name",
    enterFarmName: "Enter farm or FPO name",
    landSize: "Land Size (Acres)",
    enterLandSize: "Enter land size",
    farmAddress: "Farm Address",
    enterFarmAddress: "Enter complete farm address",
    district: "District",
    enterDistrict: "Enter district",
    state: "State",
    enterState: "Enter state",
    khasra: "Khasra Number of Land",
    enterKhasra: "Enter khasra number",
    identityBank: "Identity & Bank Details",
    aadhaar: "Aadhaar Number",
    enterAadhaar: "Enter Aadhaar number",
    pan: "PAN Number",
    enterPan: "Enter PAN number",
    bankAccount: "Bank Account Number",
    enterBankAccount: "Enter bank account number",
    ifsc: "IFSC Code",
    enterIfsc: "Enter IFSC code",
    bankName: "Bank Name",
    enterBankName: "Enter bank name",
    branchName: "Branch Name",
    enterBranch: "Enter branch name",
    verificationDocuments: "Verification Documents",
    uploadDocuments: "Upload relevant land, identity, or farming documents.",
    previous: "Previous",
    submitVerification: "Submit for Verification",
    sending: "Sending...",
    farmerDashboard: "Farmer Dashboard",
    farmerWorkspaceTitle: "Welcome to your farming workspace",
    farmerWorkspaceDescription: "Track contracts, crop progress, payouts, messages, and notifications in one place.",
    activeContracts: "Active Contracts",
    pendingPayments: "Pending Payments",
    escrowAccounts: "Escrow Accounts",
    nextBestAction: "Next best action",
    cropCommitments: "Keep your crop commitments moving",
    cropCommitmentsDescription: "Review incoming buyer requests, approve agreed terms, and keep progress updates visible to your partners.",
    reviewContracts: "Review contracts",
    yourWorkspace: "Your workspace",
    essentialsClose: "Keep the essentials close",
    addCrop: "Add a crop",
    updateProgress: "Update progress",
    checkPayouts: "Check payouts",
    farmerWorkspace: "Farmer workspace",
    buyerWorkspace: "Buyer workspace",
    adminConsole: "Admin console",
    myCrops: "My crops",
    agreements: "Agreements",
    cropProgress: "Crop progress",
    payments: "Payments",
    messages: "Messages",
    notifications: "Notifications",
    profile: "Profile",
    yourProfile: "Your Profile",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    loadingProfile: "Loading profile...",
    cropsDescription: "Add crops that you plan to cultivate and make available for contract farming opportunities.",
    closeForm: "Close Form",
    addCropContract: "Add Crop for Contract",
    viewProfile: "View Profile",
    cropMonitoring: "Crop Monitoring",
    trackCropProgress: "Track your crop progress",
    cropMonitoringDescription: "Submit regular field updates so buyers can monitor crop development, production progress, and expected harvest status.",
    earnings: "Earnings",
    farmerEarnings: "Farmer Earnings",
    earningsDescription: "Summary of settled and pending payouts linked to active contracts.",
    totalReleased: "Total released",
    pending: "Pending",
    documents: "Documents",
    farmerDocuments: "Farmer Documents",
    documentsDescription: "Upload and track verification documents and contract attachments.",
    uploadFile: "Upload File",
    uploadDocument: "Upload Document",
    notificationsTitle: "Notifications",
    noNotifications: "No notifications yet.",
    markRead: "Mark read",
    messagesTitle: "Messages",
    sendMessage: "Send a message",
    recipient: "Recipient",
    selectPartner: "Select a contract partner",
    subject: "Subject",
    message: "Message",
    send: "Send message",
    noMessages: "No messages yet.",
    communications: "Communications",
  },
  hi: {
    language: "भाषा",
    overview: "अवलोकन",
    about: "हमारे बारे में",
    features: "सुविधाएँ",
    services: "सेवाएँ",
    howItWorks: "यह कैसे काम करता है",
    contact: "संपर्क",
    register: "पंजीकरण",
    registerBuyer: "खरीदार के रूप में पंजीकरण",
    openWorkspace: "वर्कस्पेस खोलें",
    logout: "लॉगआउट",
    getStartedNav: "शुरू करें",
    secureFarming: "सुरक्षित खेती। सुनिश्चित बाजार।",
    secureLogin: "सुरक्षित लॉगिन",
    welcomeBack: "वापसी पर स्वागत है",
    email: "ईमेल",
    emailPlaceholder: "अपना ईमेल दर्ज करें",
    password: "पासवर्ड",
    login: "लॉगिन",
    newHere: "यहाँ नए हैं?",
    createAccount: "खाता बनाएँ",
    getStarted: "शुरू करें",
    chooseAccount: "अपना खाता चुनें",
    chooseAccountDescription: "किसान और खरीदार अलग-अलग पंजीकरण प्रक्रिया पूरी करते हैं ताकि सही जानकारी सत्यापित की जा सके।",
    farmerOnboarding: "किसान पंजीकरण",
    registerFarmer: "किसान के रूप में पंजीकरण",
    farmerDescription: "अपना किसान खाता बनाएँ और सत्यापित खरीदारों से जुड़ें।",
    buyerOnboarding: "खरीदार पंजीकरण",
    registerCompany: "कंपनी के रूप में पंजीकरण",
    companyDescription: "किसानों से जुड़ने और अनुबंध खेती समझौतों को संभालने के लिए कंपनी खाता बनाएँ।",
    continue: "जारी रखें",
    aboutHero: "हर फसल के लिए बेहतर अनुबंध",
    featuresHero: "पूरे खेती मौसम में स्पष्टता",
    servicesHero: "पूरे कृषि नेटवर्क के लिए एक मंच",
    howHero: "बीज योजना से भुगतान तक",
    contactHero: "AgriContract टीम से बात करें",
    homeEyebrow: "बेहतर फसल के लिए डिजिटल व्यवस्था",
    homeTitle: "विश्वास से उगाएँ। निश्चितता से बेचें।",
    homeDescription: "AgriContract किसानों, FPO और जिम्मेदार खरीदारों को सत्यापित साझेदारी, स्पष्ट अनुबंध और चरणबद्ध भुगतान से जोड़ता है।",
    registerAsFarmer: "किसान के रूप में पंजीकरण",
    registerAsCompany: "कंपनी के रूप में पंजीकरण",
    connectedNetwork: "एक जुड़ा हुआ नेटवर्क",
    networkTitle: "अच्छे अनुबंध सही लोगों से शुरू होते हैं",
    networkDescription: "पहला बीज बोने से पहले एक भरोसेमंद आपूर्ति श्रृंखला तैयार करें।",
    whyPlatform: "AgriContract क्यों",
    fairerPath: "खेत से बाजार तक एक बेहतर रास्ता",
    workflowTitle: "पूरे मौसम के लिए एक साझा रिकॉर्ड",
    workflowDescription: "अलग-अलग कॉल और स्प्रेडशीट की जगह ऐसा वर्कफ़्लो अपनाएँ जो किसानों, खरीदारों और संचालन टीमों को एक ही जानकारी दे।",
    exploreWorkflow: "वर्कफ़्लो देखें",
    step: "चरण",
    personalDetails: "व्यक्तिगत विवरण",
    farmDetails: "खेत का विवरण",
    accountDetails: "खाता विवरण",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फ़ोन नंबर",
    enterFirstName: "पहला नाम दर्ज करें",
    enterLastName: "अंतिम नाम दर्ज करें",
    enterEmail: "ईमेल पता दर्ज करें",
    enterPhone: "10 अंकों का फ़ोन नंबर दर्ज करें",
    createPassword: "मज़बूत पासवर्ड बनाएँ",
    next: "आगे",
    farmFpoName: "खेत / FPO का नाम",
    enterFarmName: "खेत या FPO का नाम दर्ज करें",
    landSize: "भूमि का आकार (एकड़)",
    enterLandSize: "भूमि का आकार दर्ज करें",
    farmAddress: "खेत का पता",
    enterFarmAddress: "खेत का पूरा पता दर्ज करें",
    district: "ज़िला",
    enterDistrict: "ज़िला दर्ज करें",
    state: "राज्य",
    enterState: "राज्य दर्ज करें",
    khasra: "भूमि का खसरा नंबर",
    enterKhasra: "खसरा नंबर दर्ज करें",
    identityBank: "पहचान और बैंक विवरण",
    aadhaar: "आधार नंबर",
    enterAadhaar: "आधार नंबर दर्ज करें",
    pan: "PAN नंबर",
    enterPan: "PAN नंबर दर्ज करें",
    bankAccount: "बैंक खाता नंबर",
    enterBankAccount: "बैंक खाता नंबर दर्ज करें",
    ifsc: "IFSC कोड",
    enterIfsc: "IFSC कोड दर्ज करें",
    bankName: "बैंक का नाम",
    enterBankName: "बैंक का नाम दर्ज करें",
    branchName: "शाखा का नाम",
    enterBranch: "शाखा का नाम दर्ज करें",
    verificationDocuments: "सत्यापन दस्तावेज़",
    uploadDocuments: "भूमि, पहचान या खेती से जुड़े दस्तावेज़ अपलोड करें।",
    previous: "पिछला",
    submitVerification: "सत्यापन के लिए भेजें",
    sending: "भेजा जा रहा है...",
    farmerDashboard: "किसान डैशबोर्ड",
    farmerWorkspaceTitle: "आपके खेती वर्कस्पेस में आपका स्वागत है",
    farmerWorkspaceDescription: "अनुबंध, फसल की प्रगति, भुगतान, संदेश और सूचनाएँ एक ही जगह देखें।",
    activeContracts: "सक्रिय अनुबंध",
    pendingPayments: "लंबित भुगतान",
    escrowAccounts: "एस्क्रो खाते",
    nextBestAction: "अगला महत्वपूर्ण काम",
    cropCommitments: "अपनी फसल प्रतिबद्धताओं को आगे बढ़ाएँ",
    cropCommitmentsDescription: "खरीदारों के अनुरोध देखें, सहमत शर्तों को मंज़ूर करें और अपने साझेदारों के लिए प्रगति अपडेट साझा रखें।",
    reviewContracts: "अनुबंध देखें",
    yourWorkspace: "आपका वर्कस्पेस",
    essentialsClose: "ज़रूरी काम पास रखें",
    addCrop: "फसल जोड़ें",
    updateProgress: "प्रगति अपडेट करें",
    checkPayouts: "भुगतान देखें",
    farmerWorkspace: "किसान वर्कस्पेस",
    buyerWorkspace: "खरीदार वर्कस्पेस",
    adminConsole: "एडमिन कंसोल",
    myCrops: "मेरी फसलें",
    agreements: "अनुबंध",
    cropProgress: "फसल की प्रगति",
    payments: "भुगतान",
    messages: "संदेश",
    notifications: "सूचनाएँ",
    profile: "प्रोफ़ाइल",
    yourProfile: "आपकी प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    cancel: "रद्द करें",
    saveChanges: "बदलाव सहेजें",
    loadingProfile: "प्रोफ़ाइल लोड हो रही है...",
    cropsDescription: "उन फसलों को जोड़ें जिन्हें आप उगाने और अनुबंध खेती के अवसरों के लिए उपलब्ध कराने की योजना बना रहे हैं।",
    closeForm: "फ़ॉर्म बंद करें",
    addCropContract: "अनुबंध के लिए फसल जोड़ें",
    viewProfile: "प्रोफ़ाइल देखें",
    cropMonitoring: "फसल निगरानी",
    trackCropProgress: "अपनी फसल की प्रगति देखें",
    cropMonitoringDescription: "नियमित खेत अपडेट भेजें ताकि खरीदार फसल विकास, उत्पादन प्रगति और अपेक्षित कटाई की स्थिति देख सकें।",
    earnings: "कमाई",
    farmerEarnings: "किसान की कमाई",
    earningsDescription: "सक्रिय अनुबंधों से जुड़े निपटाए गए और लंबित भुगतानों का सारांश।",
    totalReleased: "कुल जारी राशि",
    pending: "लंबित",
    documents: "दस्तावेज़",
    farmerDocuments: "किसान दस्तावेज़",
    documentsDescription: "सत्यापन दस्तावेज़ और अनुबंध संलग्नक अपलोड और ट्रैक करें।",
    uploadFile: "फ़ाइल अपलोड करें",
    uploadDocument: "दस्तावेज़ अपलोड करें",
    notificationsTitle: "सूचनाएँ",
    noNotifications: "अभी कोई सूचना नहीं है।",
    markRead: "पढ़ा हुआ चिह्नित करें",
    messagesTitle: "संदेश",
    sendMessage: "संदेश भेजें",
    recipient: "प्राप्तकर्ता",
    selectPartner: "अनुबंध साझेदार चुनें",
    subject: "विषय",
    message: "संदेश",
    send: "संदेश भेजें",
    noMessages: "अभी कोई संदेश नहीं है।",
    communications: "संचार",
  },
  mr: {
    language: "भाषा",
    secureLogin: "सुरक्षित लॉगिन",
    welcomeBack: "पुन्हा स्वागत आहे",
    email: "ईमेल",
    emailPlaceholder: "तुमचा ईमेल लिहा",
    password: "पासवर्ड",
    login: "लॉगिन",
    newHere: "इथे नवीन आहात?",
    createAccount: "खाते तयार करा",
    getStarted: "सुरुवात करा",
    chooseAccount: "तुमचे खाते निवडा",
    chooseAccountDescription: "योग्य माहितीची पडताळणी करण्यासाठी शेतकरी आणि खरेदीदार स्वतंत्र नोंदणी प्रक्रिया पूर्ण करतात.",
    farmerOnboarding: "शेतकरी नोंदणी",
    registerFarmer: "शेतकरी म्हणून नोंदणी",
    farmerDescription: "तुमचे शेतकरी खाते तयार करा आणि सत्यापित खरेदीदारांशी जोडा.",
    buyerOnboarding: "खरेदीदार नोंदणी",
    registerCompany: "कंपनी म्हणून नोंदणी",
    companyDescription: "शेतकऱ्यांशी जोडण्यासाठी आणि करार शेती व्यवस्थापित करण्यासाठी कंपनी खाते तयार करा.",
    continue: "पुढे जा",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("agricontract_language") || "en");
  const value = useMemo(() => ({
    language,
    setLanguage: (nextLanguage) => {
      localStorage.setItem("agricontract_language", nextLanguage);
      setLanguage(nextLanguage);
    },
    t: (key) => translations[language]?.[key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
