# Generated by Django 5.2.17 on 2026-08-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_otpverification'),
        ('contracts', '0001_initial'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='farmer.crop'),
        ),
        migrations.AddField(
            model_name='contract',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='Accounts.farmerprofile'),
        ),
    ]
