# Generated by Django 5.2.17 on 2026-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='farmer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='farmer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
    ]
