import PageHero from "../components/ui/PageHero";
import { Link } from "react-router-dom";
const data={
 about:{eyebrow:"About AgriContract",title:"A structured digital layer for contract farming",description:"AgriContract connects farmers, FPOs and buyers through verified onboarding, transparent agreements and traceable execution."},
 features:{eyebrow:"Features",title:"Everything around the contract lifecycle",description:"Onboarding, contracts, negotiation, milestones, payments, monitoring, disputes and analytics are designed as one connected workflow."},
 services:{eyebrow:"Services",title:"Tools for farmers, buyers and platform operations",description:"Give each role the tools it needs while keeping shared contract records consistent."},
 how:{eyebrow:"How It Works",title:"A traceable journey from registration to settlement",description:"Verify participants, agree terms, sign the contract, monitor milestones and release funds against verified outcomes."},
 contact:{eyebrow:"Contact",title:"Talk to the AgriContract team",description:"For pilots, buyer onboarding, farmer programs or platform questions, use the contact form below."}
};
export default function InfoPage({type}){const d=data[type];if(type==="contact")return <><PageHero {...d}/><section className="section-padding"><div className="container-page grid gap-8 lg:grid-cols-2"><div className="card"><h2 className="font-heading text-2xl font-extrabold text-navy">Send an enquiry</h2><form className="mt-6 grid gap-4" onSubmit={e=>{e.preventDefault();alert("Enquiry captured locally. Connect this form to the backend contact endpoint when ready.");}}><input className="input" placeholder="Name"/><input className="input" placeholder="Email"/><select className="input"><option>Farmer</option><option>Company / Buyer</option><option>Other</option></select><textarea className="input min-h-32" placeholder="How can we help?"/><button className="btn-primary">Submit</button></form></div><div><h2 className="font-heading text-2xl font-extrabold text-navy">What we support</h2><ul className="mt-6 grid gap-4">{["Farmer onboarding","Buyer verification","Contract workflow","Payment and milestone visibility","Monitoring and inspection","Dispute coordination"].map(x=><li className="card" key={x}>{x}</li>)}</ul></div></div></section></>;
if(type==="how")return <><PageHero {...d}/><section className="section-padding"><div className="container-page grid gap-5 md:grid-cols-2">{["Register and verify","Create contract terms","Negotiate and approve","Digitally sign","Fund escrow and track milestones","Monitor crop and inspect quality","Release milestone payment","Resolve disputes if needed"].map((x,i)=><div className="card flex gap-4" key={x}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#EAF4ED] font-bold text-primary">{i+1}</span><div><h3 className="font-heading font-bold text-navy">{x}</h3><p className="mt-2 text-sm text-slate-500">A defined step with an auditable record and role-specific action.</p></div></div>)}</div></section></>;
return <><PageHero {...d}/><section className="section-padding"><div className="container-page grid gap-5 md:grid-cols-3">{(type==="about"?["Trust and transparency","Assured market access","Paperless contract lifecycle","Regional accessibility","Traceable execution","Operational oversight"]:type==="features"?["Multi-role onboarding","Document verification","Contract templates","Negotiation history","Digital signing","Milestone tracking","Escrow ledger","Crop monitoring","Dispute resolution"]:["Farmer onboarding","Buyer procurement workflows","Contract administration","Quality inspection coordination","Payment visibility","Reporting and exports"]).map(x=><div className="card" key={x}><h3 className="font-heading text-lg font-bold text-navy">{x}</h3><p className="mt-3 text-sm leading-7 text-slate-500">Designed as a reusable platform capability rather than a one-off screen.</p></div>)}</div><div className="container-page mt-10 text-center"><Link to="/register" className="btn-primary">Get Started</Link></div></section></>}
